# Generated by Django 4.2.30 on 2026-07-27 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0007_user_email_user_nickname_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=500)),
                ('media_type', models.CharField(choices=[('drama', '드라마'), ('movie', '영화'), ('youtube', '유튜브')], max_length=20)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', '대기'), ('reviewed', '검토완료')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_suggestions', to='users.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
