import type { Media, Place, MediaPlace, Photo, Schedule, PaginatedResponse } from './types';

const MOCK_TAGS = [
  { id: 1, category: 'mood', name: '감성' },
  { id: 2, category: 'mood', name: '로맨스' },
  { id: 3, category: 'region', name: '서울' },
  { id: 4, category: 'region', name: '부산' },
];

const MOCK_PLACE: Place = {
  id: 1,
  name: '광화문 광장',
  address: '서울특별시 종로구 세종대로 172',
  latitude: '37.5759',
  longitude: '126.9768',
  image_url: 'https://picsum.photos/seed/place1/400/300',
  category: '12',
  is_verified: true,
  is_bookmarked: false,
  rating: 4.3,
  like_count: 1200,
  tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
  created_at: '2024-01-01T00:00:00Z',
};

const MOCK_PLACE_2: Place = {
  id: 2,
  name: '해운대 해수욕장',
  address: '부산광역시 해운대구 해운대해변로 264',
  latitude: '35.1587',
  longitude: '129.1604',
  image_url: 'https://picsum.photos/seed/place2/400/300',
  category: '12',
  is_verified: true,
  is_bookmarked: false,
  rating: 4.7,
  like_count: 3400,
  tags: [MOCK_TAGS[1], MOCK_TAGS[3]],
  created_at: '2024-01-01T00:00:00Z',
};

const MOCK_PLACE_3: Place = {
  id: 3,
  name: '경복궁',
  address: '서울특별시 종로구 사직로 161',
  latitude: '37.5796',
  longitude: '126.9770',
  image_url: 'https://picsum.photos/seed/place3/400/300',
  category: '14',
  is_verified: true,
  is_bookmarked: true,
  rating: 4.5,
  like_count: 8900,
  tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
  created_at: '2024-01-01T00:00:00Z',
};

const MOCK_PLACE_4: Place = {
  id: 4,
  name: '북촌 한옥마을',
  address: '서울특별시 종로구 계동길 37',
  latitude: '37.5824',
  longitude: '126.9851',
  image_url: 'https://picsum.photos/seed/place4/400/300',
  category: '14',
  is_verified: true,
  is_bookmarked: false,
  rating: 4.2,
  like_count: 5600,
  tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
  created_at: '2024-01-01T00:00:00Z',
};

const MOCK_PLACE_5: Place = {
  id: 5,
  name: '남산타워',
  address: '서울특별시 용산구 남산공원길 105',
  latitude: '37.5512',
  longitude: '126.9882',
  image_url: 'https://picsum.photos/seed/place5/400/300',
  category: '14',
  is_verified: true,
  is_bookmarked: false,
  rating: 4.6,
  like_count: 12300,
  tags: [MOCK_TAGS[1], MOCK_TAGS[2]],
  created_at: '2024-01-01T00:00:00Z',
};

const MOCK_PLACE_6: Place = {
  id: 6,
  name: '인사동 거리',
  address: '서울특별시 종로구 인사동길 44',
  latitude: '37.5744',
  longitude: '126.9855',
  image_url: 'https://picsum.photos/seed/place6/400/300',
  category: '15',
  is_verified: true,
  is_bookmarked: false,
  rating: 4.0,
  like_count: 3200,
  tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
  created_at: '2024-01-01T00:00:00Z',
};

export const MOCK_MEDIA_LIST: Media[] = [
  {
    id: 1,
    title: '도깨비',
    media_type: 'drama',
    year: 2016,
    thumbnail_url: 'https://picsum.photos/seed/media1/400/300',
    description: '불멸의 삶을 끝내줄 신부를 기다리는 도깨비와 기억을 잃은 저승사자, 그리고 도깨비 신부를 자처하는 소녀의 신비로운 러브스토리.',
    tags: [MOCK_TAGS[0], MOCK_TAGS[1]],
    is_bookmarked: false,
    place_count: 5,
    rating: 4.8,
    like_count: 3241,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    title: '이상한 변호사 우영우',
    media_type: 'drama',
    year: 2022,
    thumbnail_url: 'https://picsum.photos/seed/media2/400/300',
    description: '자폐 스펙트럼 장애를 가진 천재 변호사 우영우의 성장 이야기.',
    tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
    is_bookmarked: true,
    place_count: 3,
    rating: 4.6,
    like_count: 2187,
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 3,
    title: '범죄도시',
    media_type: 'movie',
    year: 2017,
    thumbnail_url: 'https://picsum.photos/seed/media3/400/300',
    description: '서울 금천구를 배경으로 한 형사 마석도의 액션 영화.',
    tags: [MOCK_TAGS[2]],
    is_bookmarked: false,
    place_count: 3,
    rating: 4.3,
    like_count: 1542,
    created_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 4,
    title: '응답하라 1988',
    media_type: 'drama',
    year: 2015,
    thumbnail_url: 'https://picsum.photos/seed/media4/400/300',
    description: '1988년 서울 쌍문동 골목을 배경으로 한 청춘 성장 드라마.',
    tags: [MOCK_TAGS[0], MOCK_TAGS[1]],
    is_bookmarked: false,
    place_count: 6,
    rating: 4.9,
    like_count: 4801,
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 5,
    title: '부산행',
    media_type: 'movie',
    year: 2016,
    thumbnail_url: 'https://picsum.photos/seed/media5/400/300',
    description: '부산으로 향하는 KTX 열차 안에서 벌어지는 좀비 재난 영화.',
    tags: [MOCK_TAGS[3]],
    is_bookmarked: false,
    place_count: 4,
    rating: 4.1,
    like_count: 987,
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 6,
    title: '사랑의 불시착',
    media_type: 'drama',
    year: 2019,
    thumbnail_url: 'https://picsum.photos/seed/media6/400/300',
    description: '패러글라이딩 사고로 북한에 불시착한 재벌 상속녀와 북한 장교의 로맨스.',
    tags: [MOCK_TAGS[1], MOCK_TAGS[2]],
    is_bookmarked: true,
    place_count: 3,
    rating: 4.7,
    like_count: 2934,
    created_at: '2024-01-06T00:00:00Z',
  },
  {
    id: 7,
    title: '기생충',
    media_type: 'movie',
    year: 2019,
    thumbnail_url: 'https://picsum.photos/seed/media7/400/300',
    description: '전원 백수인 기택 가족과 부유한 박 사장 가족의 이야기.',
    tags: [MOCK_TAGS[0], MOCK_TAGS[2]],
    is_bookmarked: false,
    place_count: 9,
    rating: 4.5,
    like_count: 2103,
    created_at: '2024-01-07T00:00:00Z',
  },
  {
    id: 8,
    title: '갯마을 차차차',
    media_type: 'drama',
    year: 2021,
    thumbnail_url: 'https://picsum.photos/seed/media8/400/300',
    description: '바닷마을 공진에서 펼쳐지는 치과의사와 백수건달의 로맨스.',
    tags: [MOCK_TAGS[1], MOCK_TAGS[3]],
    is_bookmarked: false,
    place_count: 6,
    rating: 4.4,
    like_count: 1678,
    created_at: '2024-01-08T00:00:00Z',
  },
];

export const MOCK_MEDIA_PLACES: MediaPlace[] = [
  {
    id: 1,
    place: MOCK_PLACE,
    day: 1,
    scene_description: '주인공이 처음 만나는 장소',
    confidence_score: 0.95,
    is_confirmed: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    place: MOCK_PLACE_2,
    day: 1,
    scene_description: '바다를 바라보는 장면',
    confidence_score: 0.88,
    is_confirmed: true,
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 3,
    place: MOCK_PLACE_3,
    day: 2,
    scene_description: '역사적인 배경 장면',
    confidence_score: 0.92,
    is_confirmed: true,
    created_at: '2024-01-01T00:00:00Z',
  },
];

// 미디어 ID별 장소 목록 — importToSchedule 시 daily_places 생성에 사용
export const MOCK_MEDIA_PLACES_MAP: Record<number, MediaPlace[]> = {
  1: [ // 도깨비
    { id: 1, place: MOCK_PLACE,    day: 1, scene_description: '', confidence_score: 0.95, is_confirmed: true, created_at: '' },
    { id: 2, place: MOCK_PLACE_4,  day: 1, scene_description: '', confidence_score: 0.90, is_confirmed: true, created_at: '' },
    { id: 3, place: MOCK_PLACE_5,  day: 1, scene_description: '', confidence_score: 0.88, is_confirmed: true, created_at: '' },
    { id: 4, place: MOCK_PLACE_2,  day: 2, scene_description: '', confidence_score: 0.85, is_confirmed: true, created_at: '' },
    { id: 5, place: MOCK_PLACE_6,  day: 2, scene_description: '', confidence_score: 0.82, is_confirmed: true, created_at: '' },
  ],
  2: [ // 이상한 변호사 우영우
    { id: 6, place: MOCK_PLACE_3,  day: 1, scene_description: '', confidence_score: 0.93, is_confirmed: true, created_at: '' },
    { id: 7, place: MOCK_PLACE_6,  day: 1, scene_description: '', confidence_score: 0.88, is_confirmed: true, created_at: '' },
    { id: 8, place: MOCK_PLACE,    day: 2, scene_description: '', confidence_score: 0.85, is_confirmed: true, created_at: '' },
    { id: 9, place: MOCK_PLACE_5,  day: 2, scene_description: '', confidence_score: 0.80, is_confirmed: true, created_at: '' },
    { id: 10, place: MOCK_PLACE_4, day: 3, scene_description: '', confidence_score: 0.78, is_confirmed: true, created_at: '' },
  ],
  6: [ // 사랑의 불시착
    { id: 11, place: MOCK_PLACE_5, day: 1, scene_description: '', confidence_score: 0.91, is_confirmed: true, created_at: '' },
    { id: 12, place: MOCK_PLACE,   day: 2, scene_description: '', confidence_score: 0.87, is_confirmed: true, created_at: '' },
    { id: 13, place: MOCK_PLACE_3, day: 2, scene_description: '', confidence_score: 0.84, is_confirmed: true, created_at: '' },
  ],
};

export const MOCK_PHOTOS: Photo[] = [
  {
    id: 1,
    image_url: 'https://picsum.photos/seed/photo1/400/300',
    description: '아름다운 일몰',
    likes: 120,
    tags: [MOCK_TAGS[0]],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    image_url: 'https://picsum.photos/seed/photo2/400/300',
    description: '도심 야경',
    likes: 85,
    tags: [MOCK_TAGS[2]],
    created_at: '2024-01-02T00:00:00Z',
  },
];

export const MOCK_SCHEDULES: Schedule[] = [
  {
    id: 1,
    title: '도깨비 여행코스',
    media: { id: 1, title: '도깨비', thumbnail_url: 'https://picsum.photos/seed/media1/400/300', media_type: 'drama', tags: [MOCK_TAGS[0], MOCK_TAGS[1]], place_count: 7 },
    start_date: '2026-06-13',
    end_date: '2026-06-15',
    is_bookmarked: true,
    daily_places: [
      { id: 1, day_number: 1, order: 1, memo: '', place: MOCK_PLACE },
      { id: 2, day_number: 1, order: 2, memo: '', place: MOCK_PLACE_4 },
      { id: 3, day_number: 1, order: 3, memo: '', place: MOCK_PLACE_5 },
      { id: 4, day_number: 2, order: 1, memo: '', place: MOCK_PLACE_2 },
      { id: 5, day_number: 2, order: 2, memo: '', place: MOCK_PLACE_6 },
      { id: 6, day_number: 3, order: 1, memo: '', place: MOCK_PLACE_3 },
      { id: 7, day_number: 3, order: 2, memo: '', place: MOCK_PLACE_4 },
    ],
    created_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 2,
    title: '우영우 서울 탐방',
    media: { id: 2, title: '이상한 변호사 우영우', thumbnail_url: 'https://picsum.photos/seed/media2/400/300', media_type: 'drama', tags: [MOCK_TAGS[0], MOCK_TAGS[2]], place_count: 5 },
    start_date: '2026-07-05',
    end_date: '2026-07-07',
    is_bookmarked: false,
    daily_places: [
      { id: 8,  day_number: 1, order: 1, memo: '', place: MOCK_PLACE_3 },
      { id: 9,  day_number: 1, order: 2, memo: '', place: MOCK_PLACE_6 },
      { id: 10, day_number: 2, order: 1, memo: '', place: MOCK_PLACE },
      { id: 11, day_number: 2, order: 2, memo: '', place: MOCK_PLACE_5 },
      { id: 12, day_number: 3, order: 1, memo: '', place: MOCK_PLACE_4 },
    ],
    created_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 3,
    title: '부산 영화 투어',
    media: { id: 5, title: '부산행', thumbnail_url: 'https://picsum.photos/seed/media5/400/300', media_type: 'movie', tags: [MOCK_TAGS[3]], place_count: 3 },
    start_date: '2026-08-10',
    end_date: '2026-08-11',
    is_bookmarked: false,
    daily_places: [],
    created_at: '2024-01-05T00:00:00Z',
  },
  {
    id: 4,
    title: '응답하라 1988 성지순례',
    media: { id: 4, title: '응답하라 1988', thumbnail_url: 'https://picsum.photos/seed/media4/400/300', media_type: 'drama', tags: [MOCK_TAGS[0], MOCK_TAGS[1]], place_count: 2 },
    start_date: '2026-05-01',
    end_date: '2026-05-03',
    is_bookmarked: false,
    daily_places: [
      { id: 5, day_number: 1, order: 1, memo: '', place: MOCK_PLACE },
      { id: 6, day_number: 2, order: 1, memo: '', place: MOCK_PLACE_3 },
    ],
    created_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 5,
    title: '기생충 촬영지 투어',
    media: { id: 7, title: '기생충', thumbnail_url: 'https://picsum.photos/seed/media7/400/300', media_type: 'movie', tags: [MOCK_TAGS[0], MOCK_TAGS[2]], place_count: 1 },
    start_date: '2026-04-10',
    end_date: '2026-04-11',
    is_bookmarked: true,
    daily_places: [
      { id: 7, day_number: 1, order: 1, memo: '', place: MOCK_PLACE_2 },
    ],
    created_at: '2024-01-07T00:00:00Z',
  },
];

// 런타임에 생성된 일정을 포함하는 mutable store — getList/getDetail/importToSchedule이 공유
export const mockScheduleStore: Schedule[] = [...MOCK_SCHEDULES];

// 전체 장소 mutable store — bookmark/unbookmark 시 is_bookmarked를 실제로 변경
export const mockPlaceStore: Place[] = [
  MOCK_PLACE, MOCK_PLACE_2, MOCK_PLACE_3, MOCK_PLACE_4, MOCK_PLACE_5, MOCK_PLACE_6,
];

export function paginatedOf<T>(results: T[]): PaginatedResponse<T> {
  return { count: results.length, next: null, previous: null, results };
}
