# Generated by Django 4.2.30 on 2026-07-22 06:56 (수정: is_approved → status 데이터 이관 순서 조정)

from django.db import migrations, models
import django.db.models.deletion


def migrate_is_approved_to_status(apps, schema_editor):
    Photo = apps.get_model('places', 'Photo')
    Photo.objects.filter(is_approved=False).update(status='pending')


def migrate_status_to_is_approved(apps, schema_editor):
    Photo = apps.get_model('places', 'Photo')
    Photo.objects.exclude(status='approved').update(is_approved=False)
    Photo.objects.filter(status='approved').update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_photo_is_approved_photo_last_rewarded_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='publish_reward_granted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.CharField(choices=[('approved', '승인'), ('pending', '심사중'), ('rejected', '반려')], default='approved', max_length=20),
        ),
        migrations.CreateModel(
            name='PhotoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='places.photo')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RunPython(migrate_is_approved_to_status, migrate_status_to_is_approved),
        migrations.RemoveField(
            model_name='photo',
            name='is_approved',
        ),
    ]
