# Generated by Django 4.2.30 on 2026-07-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_remove_photo_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='moderation_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
