# Generated by Django 4.2.30 on 2026-07-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_photo_moderation_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='photo',
            name='travel_date',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
