# Generated by Django 4.2.30 on 2026-07-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0012_photo_content_photo_travel_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistExtractionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_url', models.URLField(max_length=500)),
                ('media_title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('drama', '드라마'), ('movie', '영화'), ('youtube', '유튜브'), ('etc', '기타')], default='youtube', max_length=20)),
                ('ai_choice', models.CharField(default='gemini', max_length=20)),
                ('fallback_ai_choice', models.CharField(default='gemini', max_length=20)),
                ('scene', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('running', '진행중'), ('done', '완료'), ('cancelled', '취소됨')], default='running', max_length=20)),
                ('cancel_requested', models.CharField(blank=True, choices=[('', '요청 없음'), ('immediate', '즉시 취소'), ('graceful', '완료 후 종료')], default='', max_length=20)),
                ('videos', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=-1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mediaplace',
            name='source_video_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
