# Generated by Django 4.2.30 on 2026-07-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_playlistextractionjob_mediaplace_source_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistextractionjob',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
    ]
