# Generated by Django 4.2.30 on 2026-07-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_playlistextractionjob_cancel_requested'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistFetchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_url', models.URLField(max_length=500)),
                ('status', models.CharField(choices=[('running', '조회중'), ('done', '완료'), ('error', '오류')], default='running', max_length=20)),
                ('videos', models.JSONField(default=list)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
