# Generated by Django 4.2.30 on 2026-07-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0015_playlistfetchjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistfetchjob',
            name='media_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
