# Generated by Django 4.2.30 on 2026-07-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_playlistfetchjob_media_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistextractionjob',
            name='merge_videos',
            field=models.BooleanField(default=False),
        ),
    ]
