# Generated by Django 4.2.30 on 2026-08-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0017_playlistextractionjob_merge_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('media_type', '미디어 유형'), ('genre', '장르'), ('place_type', '장소 유형'), ('photo_custom', '포토스팟 자유 태그')], max_length=20),
        ),
    ]
