# Generated by Django 4.2.30 on 2026-08-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
