# Generated by Django 4.2.30 on 2026-08-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_place_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='business_hours',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
