# Generated by Django 4.2.30 on 2026-08-26 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0020_place_business_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
