# Generated by Django 4.2.30 on 2026-09-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0021_place_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_photo_author_avatar_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='google_photo_author_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='google_photo_author_uri',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='google_photo_maps_uri',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='google_photo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='google_photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
