# Generated by Django 4.2.30 on 2026-09-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_place_google_photo_author_avatar_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='google_photo_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
