# Generated by Django 4.2.30 on 2026-09-08 03:53
from django.db import migrations
from django.db.models import Value
from django.db.models.functions import Replace


def upgrade_to_https(apps, schema_editor):
    """관광공사(KTO) API가 http://로 내려주던 image_url을 https://로 일괄 승격.
    Android 9+ 기본 cleartext 차단으로 http:// 이미지가 앱에서 로드 실패하던 문제를
    이미 저장된 기존 행에도 소급 적용한다(신규 저장분은 services._kto_image_url이 처리)."""
    Place = apps.get_model('places', 'Place')
    Place.objects.filter(image_url__startswith='http://').update(
        image_url=Replace('image_url', Value('http://'), Value('https://'))
    )


def downgrade_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_place_google_photo_path'),
    ]

    operations = [
        migrations.RunPython(upgrade_to_https, downgrade_noop),
    ]
