# Generated by Django 4.2.30 on 2026-09-09 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_backfill_https_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='kto_photo_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='kto_photo_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
