# Generated by Django 4.2.30 on 2026-07-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='is_probable_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='weight',
            field=models.FloatField(default=1.0),
        ),
    ]
