"""
Django settings for YogiEoddae project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import environ
import os

from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 배포 환경에서는 Railway 등 환경변수에 SECRET_KEY를 새로 발급해 넣을 것 (아래 default는 로컬 개발용)
SECRET_KEY = env('SECRET_KEY', default='django-insecure-snr@nu(e$fi4_2+45md-(x%(_05&qn(%lx8ezx3vyu=6gqn!%3')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=True)

# .up.railway.app는 Railway가 배포 시 자동 발급하는 도메인이라 미리 허용해둠
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    'localhost', '127.0.0.1', '192.168.0.6', '192.168.0.7',
    '.ngrok-free.app', '.ngrok-free.dev', '.ngrok.io', '.up.railway.app',
])

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://*.up.railway.app'])

# Railway는 바깥에서 HTTPS로 받아 내부적으로 앱엔 HTTP로 전달하는 리버스 프록시 구조라,
# 이 설정이 없으면 request.is_secure()가 항상 False로 판단돼 build_absolute_uri() 등이
# http:// URL을 만들어버림 (업로드 이미지 URL이 http://가 되어 AI 검열 다운로드 실패 + 안드로이드
# cleartext 차단으로 앱에서 이미지 로드 실패를 일으키던 원인, 2026-08-15 발견).
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'places',
    'users',
    'schedules',
    'bookmarks',
    'reviews',
    'mailbox',
    'course_suggestions',
    'quiz',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'users.middleware.UpdateLastActiveMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'YogiEoddae.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YogiEoddae.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': env.db()
}


# Password hashing
# https://docs.djangoproject.com/en/4.2/topics/auth/passwords/#using-bcrypt-with-django

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
]


# JWT (커스텀 User 모델용 — PyJWT로 직접 발급/검증, djangorestframework-simplejwt 미사용)

JWT_ACCESS_TOKEN_LIFETIME_MINUTES = 30
JWT_REFRESH_TOKEN_LIFETIME_DAYS = 14


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# 유저 업로드 이미지(포토스팟 등). 배포 시 S3/R2 등으로 전환 예정 — DEVPLAN.md "이미지 스토리지 배포 전환 가이드" 참고.
# Railway 배포 시 이 경로에 Volume을 마운트해야 재배포 후에도 업로드 이미지가 유지됨.
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # 개발 중 브라우저에서 바로 확인용
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    # JWT를 넣어 보내면 request.user가 채워지고, 안 보내면 AnonymousUser로 남는다
    # (permission_classes로 IsAuthenticated를 명시한 뷰에서만 로그인이 강제됨).
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.JWTAuthentication',
    ],
}

# .env에서 읽어온 환경 변수들을 장고 설정값으로 등록
TOUR_API_KEY = env('TOUR_API_KEY')
NAVER_CLIENT_ID = env('NAVER_CLIENT_ID')
NAVER_CLIENT_SECRET = env('NAVER_CLIENT_SECRET')
KAKAO_JS_KEY  = env('KAKAO_JS_KEY')
KAKAO_REST_KEY = env('KAKAO_REST_KEY', default='')
ANTHROPIC_API_KEY = env('ANTHROPIC_API_KEY', default='')
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')
YOUTUBE_API_KEY = env('YOUTUBE_API_KEY', default='')
DEVICE_ID_HASH_KEY = env('DEVICE_ID_HASH_KEY')

# 이메일 발송 (Gmail SMTP) — .env에 EMAIL_HOST_USER/EMAIL_HOST_PASSWORD(앱 비밀번호)가 없으면
# 콘솔 출력으로 자동 대체되어 로컬 개발 중에도 크래시 없이 동작한다.
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'noreply@yogieoddae.local'

if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
    # 배포 환경에서 587 포트로 나가는 연결이 막혀있으면 소켓 connect()가 응답 없이
    # 무한 대기하다 gunicorn 자체 타임아웃(기본 30초)에 워커 프로세스 전체가
    # SIGABRT로 죽는 문제가 있었음(2026-08-18 Railway 배포 로그로 확인).
    # 타임아웃을 짧게 걸어서 워커를 죽이는 대신 예외로 빨리 실패하게 한다.
    EMAIL_TIMEOUT = 10
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Kakao Maps SDK 403 방지: Referer 헤더를 크로스 오리진 요청에도 포함
SECURE_REFERRER_POLICY = 'no-referrer-when-downgrade'

# CORS — React Native 개발 서버 허용 (배포 시 실제 도메인으로 교체)
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-device-id",
    "ngrok-skip-browser-warning",
    "cache-control",
    "pragma",
]