# Generated by Django 4.2.30 on 2026-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_device_id_finalize_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
